contact:
    host: "${MAIL_CONTACT_HOST}"
    port: "${MAIL_CONTACT_PORT}"
    username: "${MAIL_CONTACT_USERNAME}"
    password: "${MAIL_CONTACT_PASSWORD}"
    encryption: "${MAIL_CONTACT_ENCRYPTION}"
    from:
      email: "${MAIL_CONTACT_FROM_EMAIL}"
      name: "${MAIL_CONTACT_FROM_NAME}"
    subject: "${MAIL_CONTACT_SUBJECT}"

tickets:
  host: "${MAIL_TICKETS_HOST}"
  port: "${MAIL_TICKETS_PORT}"
  username: "${MAIL_TICKETS_USERNAME}"
  password: "${MAIL_TICKETS_PASSWORD}"
  encryption: "${MAIL_TICKETS_ENCRYPTION}"
  from:
    email: "${MAIL_TICKETS_FROM_EMAIL}"
    name: "${MAIL_TICKETS_FROM_NAME}"
  subject: "${MAIL_TICKETS_SUBJECT}"
