contact:
  method: POST
  path: /contact
  handlers:
    - App\Handler\EmptyBodyRequestHandler
    - App\Handler\JsonRequestHandler
    - class: App\Handler\ReCaptchaHandler
      arguments:
        - 'contact'
    - App\Handler\Contact\ValidationHandler
    - App\Handler\Contact\RenderTemplateHandler
    - class: App\Handler\MailHandler
      arguments:
        - 'contact'
    - App\Handler\Contact\FinishHandler

tickets:
  method: POST
  path: /tickets
  handlers:
    - App\Handler\EmptyBodyRequestHandler
    - App\Handler\JsonRequestHandler
    - class: App\Handler\ReCaptchaHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\ValidationHandler
    - App\Handler\Tickets\RenderTemplateHandler
    - class: App\Handler\MailHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\FinishHandler

tickets_events:
  method: GET
  path: /tickets/events
  handlers:
    - App\Handler\Tickets\EventsListHandler

tickets_tickets:
  method: GET
  path: /tickets/tickets
  handlers:
    - App\Handler\Tickets\TicketsListHandler
