contact:
  method: POST
  path: /contact
  handlers:
    - App\Handler\EmptyBodyRequestHandler
    - App\Handler\JsonRequestHandler
    - class: App\Handler\ReCaptchaHandler
      arguments:
        - 'contact'
    - App\Handler\Contact\ValidationHandler
    - App\Handler\Contact\RenderTemplateHandler
    - class: App\Handler\MailHandler
      arguments:
        - 'contact'
    - App\Handler\Contact\FinishHandler

tickets:
  method: POST
  path: /tickets
  handlers:
    - App\Handler\EmptyBodyRequestHandler
    - App\Handler\JsonRequestHandler
    - class: App\Handler\ReCaptchaHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\General\ValidationHandler
    - App\Handler\Tickets\General\RenderTemplateHandler
    - class: App\Handler\MailHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\FinishHandler

tickets_events:
  method: GET
  path: /tickets/events
  handlers:
    - App\Handler\Tickets\EventsListHandler

tickets_tickets:
  method: GET
  path: /tickets/tickets
  handlers:
    - App\Handler\Tickets\TicketsListHandler

school_tickets:
  method: POST
  path: /school/tickets
  handlers:
    - App\Handler\EmptyBodyRequestHandler
    - App\Handler\JsonRequestHandler
    - class: App\Handler\ReCaptchaHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\School\ValidationHandler
    - App\Handler\Tickets\School\RenderTemplateHandler
    - class: App\Handler\MailHandler
      arguments:
        - 'tickets'
    - App\Handler\Tickets\FinishHandler

school_tickets_events:
  method: GET
  path: /school/tickets/events
  handlers:
    - App\Handler\Tickets\EventsListHandler

school_tickets_tickets:
  method: GET
  path: /school/tickets/tickets
  handlers:
    - class: App\Handler\Tickets\TicketsListHandler
      arguments:
        - true
